<?xml version="1.0"?>
<package format="2">
  <name>gaussian_mixture</name>
  <version>1.0.0</version>
  <description>A package to commpute gaussian mixture from images</description>
  <maintainer email="jocelyn.buisson@utbm.fr">Jocelyn Buisson</maintainer>

  <url type="website">https://epan-utbm.github.io/</url>

  <author email="jocelyn.buisson@utbm.fr">Jocelyn Buisson</author>

  <license>Proprietary</license>

 <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>ros_numpy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>ros_numpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
