#!/usr/bin/env python3

import rospy
import torch
import torch.fft                         as fft
import torch.nn.functional               as F
import torchvision.transforms.functional as Fv

from numbers import Number
from typing  import Iterable, Tuple, Union
from PIL     import Image as PILImage
import time

import numpy as np

np.float = np.float64

from ros_numpy       import msgify, numpify
from sensor_msgs.msg import Image
import cv2
import numpy as np

from gaussian_mixture.srv import (
    ComputeGaussianMixture,
    ComputeGaussianMixtureResponse,
    ComputeOrientedGaussianMixture,
    ComputeOrientedGaussianMixtureResponse,
    ComputePhotometricEllipticalGaussianMixture,
    ComputePhotometricEllipticalGaussianMixtureResponse
)

def make_tuple(x: Union[int, Iterable[int]], n: int) -> Tuple[int, ...]:
    """
    Converts a single value or an interable to a tuple of length n.

    Parameters
    ----------
    :param x: Union[int, Iterable[int]]
        the value to convert.

    :param n: int
        the length of the tuple to generate.

    Returns
    -------
    :return: Tuple[int, ...]
        the generated tuple.
    """
    return tuple(x) if isinstance(x, Iterable) else (x,)*n

def fft_conv2d(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor = None, stride: Union[int, Iterable[int]] = 1, padding: Union[int, Iterable[int]] = 0, groups: int = 1) -> torch.Tensor:
    padding = make_tuple(padding, 2)
    assert len(padding) == 2, f"Expected padding to be a single integer value or a list of 2 values to match the convolution dimensions, but got padding={len(padding)}"

    stride = make_tuple(stride, 2)
    assert len(stride) == 2, f"Expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride={len(stride)}"

    xN, xC, xH, xW = x.shape
    oC, iC, kH, kW = weight.shape

    pad_y, pad_x = padding
    pad_l = (xW + 2*pad_x) % 2
    x = F.pad(x, (pad_x, pad_x+pad_l, pad_y, pad_y))

    pH, pW = x.shape[-2:]

    k = F.pad(weight, (0, pW - kW, 0, pH - kH))

    x = fft.rfftn(x.view(xN, groups, xC//groups,  1, pH, pW), dim=(-2, -1))
    k = fft.rfftn(k.view(1,  groups, oC//groups, iC, pH, pW), dim=(-2, -1))

    k.imag *= -1

    y = torch.squeeze(k.permute(0, 1, 4, 5, 2, 3) @ x.permute(0, 1, 4, 5, 2, 3), dim=-1)
    y = fft.irfftn(y.permute(0, 1, 4, 2, 3), dim=(-2, -1)).reshape(xN, -1, pH, pW)

    crop_slices = [
        slice(0, xN),
        slice(0, oC),
        slice(0, pH - kH + 1, stride[1]),
        slice(0, pW - kW + 1, stride[0])
    ]
    y = y[crop_slices].contiguous()

    if bias is not None:
        y += bias.view(1, oC, 1, 1)
    return y

def fft_conv2d_circular(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor = None, stride: Union[int, Iterable[int]] = 1, padding: Union[int, Iterable[int]] = 0, groups: int = 1) -> torch.Tensor:
    padding = make_tuple(padding, 2)
    assert len(padding) == 2, f"Expected padding to be a single integer value or a list of 2 values to match the convolution dimensions, but got padding={len(padding)}"

    stride = make_tuple(stride, 2)
    assert len(stride) == 2, f"Expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride={len(stride)}"

    xN, xC, xH, xW = x.shape
    oC, iC, kH, kW = weight.shape

    pad_y, pad_x = padding
    pad_l = (xW + 2*pad_x) % 2
    x = F.pad(x, (pad_x, pad_x+pad_l, pad_y, pad_y), mode='circular')

    pH, pW = x.shape[-2:]

    k = F.pad(weight, (0, pW - kW, 0, pH - kH))
    k = torch.fft.ifftshift(k, dim=(-2, -1))

    x = fft.rfftn(x.view(xN, groups, xC//groups,  1, pH, pW), dim=(-2, -1))
    k = fft.rfftn(k.view(1,  groups, oC//groups, iC, pH, pW), dim=(-2, -1))

    k.imag *= -1

    y = torch.squeeze(k.permute(0, 1, 4, 5, 2, 3) @ x.permute(0, 1, 4, 5, 2, 3), dim=-1)
    y = fft.irfftn(y.permute(0, 1, 4, 2, 3), dim=(-2, -1)).reshape(xN, -1, pH, pW)

    # crop_slices = [
    #     slice(0, xN),
    #     slice(0, oC),
    #     slice(0, pH - kH + 1, stride[1]),
    #     slice(0, pW - kW + 1, stride[0])
    # ]
    # y = y[crop_slices].contiguous()

    if bias is not None:
        y += bias.view(1, oC, 1, 1)
    return y

def gaussian_mixture(x: torch.Tensor, beta: Union[Number, torch.Tensor], derivatives: bool = False) -> Union[torch.Tensor, Tuple[torch.Tensor, ...]]:
    N, C, H, W = x.shape

    if isinstance(beta, Number):
        beta = torch.full((1, C, 1, 1), beta, device=x.device)

    dv = torch.linspace(H-1, -H+1, 2*H-1, device=x.device).view(1, 1, -1, 1)
    du = torch.linspace(W-1, -W+1, 2*W-1, device=x.device).view(1, 1, 1, -1)
    Kg = torch.exp(beta * (du**2 + dv**2))

    if derivatives:
        Kdu = Kg * du * 2.0 * beta
        Kdv = Kg * dv * 2.0 * beta
        Kdb = Kg * (du**2 + dv**2)
        K = torch.cat((Kg, torch.stack((Kdu, Kdv), dim=2).flatten(1, 2), Kdb), dim=1)
        y = fft_conv2d(x, K.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)
        return F.pad(y, (0, 0, 0, 0)).split((C, C, C, C), dim=1)

    else:
        return fft_conv2d(x, Kg.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)

def gaussian_mixture_lambda(x: torch.Tensor, lambda_: Union[Number, torch.Tensor], derivatives: bool = False) -> Union[
    torch.Tensor, Tuple[torch.Tensor, ...]]:
    N, C, H, W = x.shape

    if isinstance(lambda_, Number):
        lambda_ = torch.full((1, C, 1, 1), lambda_, device=x.device)

    dv = torch.linspace(H/2, -H/2, H, device=x.device).view(1, 1, -1, 1)
    du = torch.linspace(W/2, -W/2, W, device=x.device).view(1, 1, 1, -1)
    Kg = torch.exp(-(du ** 2 + dv ** 2)/(2 * lambda_ ** 2))

    if derivatives:
        Kdu = -Kg * du / lambda_ ** 2
        Kdv = -Kg * dv / lambda_ ** 2
        Kdl = Kg * ((du ** 2 + dv ** 2) / lambda_ ** 3)
        K = torch.cat((Kg, torch.stack((Kdu, Kdv), dim=2).flatten(1, 2), Kdl), dim=1)
        y = fft_conv2d(x, K.flatten(0, 1).unsqueeze(1), padding=(H//2, W//2), groups=C)
        y = Fv.crop(y, 0, 0, H, W)
        return y.split((C, C, C, C), dim=1)

    else:
        return fft_conv2d(x, Kg.flatten(0, 1).unsqueeze(1), padding=(H - 1, W - 1), groups=C)

def gaussian_mixture_lambda_circular(x: torch.Tensor, lambda_: Union[Number, torch.Tensor], derivatives: bool = False) -> Union[
    torch.Tensor, Tuple[torch.Tensor, ...]]:
    N, C, H, W = x.shape

    if isinstance(lambda_, Number):
        lambda_ = torch.full((1, C, 1, 1), lambda_, device=x.device)

    scale = 1  # must be odd (1, 3, 5, etc.)

    if scale > 1:
        x = torch.cat([x]*scale, dim=-1)
        x = torch.cat([x]*scale, dim=-2)
        H *= scale
        W *= scale

    dv = torch.linspace(H/2, -H/2, H, device=x.device).view(1, 1, -1, 1)
    du = torch.linspace(W/2, -W/2, W, device=x.device).view(1, 1, 1, -1)
    Kg = torch.exp(-(du ** 2 + dv ** 2)/(2 * lambda_ ** 2))

    if derivatives:
        Kdu = -Kg * du / lambda_ ** 2
        Kdv = -Kg * dv / lambda_ ** 2
        Kdl = Kg * ((du ** 2 + dv ** 2) / lambda_ ** 3)
        K = torch.cat((Kg, torch.stack((Kdu, Kdv), dim=2).flatten(1, 2), Kdl), dim=1)
        y = fft_conv2d_circular(x, K.flatten(0, 1).unsqueeze(1), groups=C)
        if scale > 1:
            H //= scale
            W //= scale
            y = Fv.crop(y, scale//2*H, scale//2*W, H, W)
        return y.split((C, C, C, C), dim=1)

    else:
        return fft_conv2d(x, Kg.flatten(0, 1).unsqueeze(1), padding=(H - 1, W - 1), groups=C)

def oriented_gaussian_mixture(x: torch.Tensor, beta: Union[Number, torch.Tensor], ratio: Union[Number, torch.Tensor], theta: Union[Number, torch.Tensor], derivatives: bool = False) -> Union[torch.Tensor, Tuple[torch.Tensor, ...]]:
    N, C, H, W = x.shape

    if isinstance(beta, Number):
        beta = torch.full((1, C, 1, 1), beta, device=x.device)
    if isinstance(ratio, Number):
        ratio = torch.full((1, 1, 1, 1), ratio, device=x.device)
    if isinstance(theta, Number):
        theta = torch.full((1, 1, 1, 1), theta, device=x.device)

    bi = beta
    bj = beta * ratio

    a = (bi * torch.cos(theta)**2 + bj * torch.sin(theta)**2).view(1, -1, 1, 1)
    b = ((bj - bi) * torch.sin(2.0 * theta)).view(N, -1, 1, 1)
    c = (bi * torch.sin(theta)**2 + bj * torch.cos(theta)**2).view(1, -1, 1, 1)

    dv = torch.linspace(H-1, -H+1, 2*H-1, device=x.device).view(1, 1, -1, 1)
    du = torch.linspace(W-1, -W+1, 2*W-1, device=x.device).view(1, 1, 1, -1)
    Kg = torch.exp(-(a * du**2 + b * dv @ du + c * dv**2))

    if derivatives:
        Kdu = -Kg * (
            dv * (bi * torch.sin(2.0 * theta) - bj * torch.sin(2.0 * theta)) +
            du * 2.0 * (bi * torch.cos(theta)**2 + bj * torch.sin(theta)**2)
        )
        Kdv = -Kg * (
            du * (bi * torch.sin(2.0 * theta) - bj * torch.sin(2.0 * theta)) +
            dv * 2.0 * (bi * torch.sin(theta)**2 + bj * torch.cos(theta)**2)
        )
        Kdb = -Kg * (
            du**2 * (torch.cos(theta)**2 + ratio * torch.sin(theta)**2) +
            du*dv *  torch.sin(2.0 * theta) * (1.0 - ratio)             +
            dv**2 * (torch.sin(theta)**2 + ratio * torch.cos(theta)**2)
        )
        K = torch.cat((Kg, torch.stack((Kdu, Kdv), dim=2).flatten(1, 2), Kdb), dim=1)
        y = fft_conv2d(x, K.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)
        return y.split((C, C, C, C), dim=1)

    else:
        return fft_conv2d(x, Kg.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)


def photometric_elliptical_gaussian_mixture(x: torch.Tensor, beta: Union[Number, torch.Tensor], ratio: Union[Number, torch.Tensor], theta: Union[Number, torch.Tensor], Imin: int, Imax: int,  derivatives: bool = False) -> Union[torch.Tensor, Tuple[torch.Tensor, ...]]:
    N, C, H, W = x.shape

    if isinstance(beta, Number):
        beta = torch.full((1, C, 1, 1), beta, device=x.device)
    if isinstance(ratio, Number):
        ratio = torch.full((1, 1, 1, 1), ratio, device=x.device)
    if isinstance(theta, Number):
        theta = torch.full((1, 1, 1, 1), theta, device=x.device)

    x *= torch.logical_and((x >= Imin/255), (x < Imax/255))

    bi = beta
    bj = beta * ratio

    a = (bi * torch.cos(theta)**2 + bj * torch.sin(theta)**2).view(1, -1, 1, 1)
    b = ((bj - bi) * torch.sin(2.0 * theta)).view(N, -1, 1, 1)
    c = (bi * torch.sin(theta)**2 + bj * torch.cos(theta)**2).view(1, -1, 1, 1)

    dv = torch.linspace(H-1, -H+1, 2*H-1, device=x.device).view(1, 1, -1, 1)
    du = torch.linspace(W-1, -W+1, 2*W-1, device=x.device).view(1, 1, 1, -1)
    Kg = torch.exp(-(a * du**2 + b * dv @ du + c * dv**2))

    if derivatives:
        Kdu = -Kg * (
            dv * (bi * torch.sin(2.0 * theta) - bj * torch.sin(2.0 * theta)) +
            du * 2.0 * (bi * torch.cos(theta)**2 + bj * torch.sin(theta)**2)
        )
        Kdv = -Kg * (
            du * (bi * torch.sin(2.0 * theta) - bj * torch.sin(2.0 * theta)) +
            dv * 2.0 * (bi * torch.sin(theta)**2 + bj * torch.cos(theta)**2)
        )
        Kdb = -Kg * (
            du**2 * (torch.cos(theta)**2 + ratio * torch.sin(theta)**2) +
            du*dv *  torch.sin(2.0 * theta) * (1.0 - ratio)             +
            dv**2 * (torch.sin(theta)**2 + ratio * torch.cos(theta)**2)
        )
        K = torch.cat((Kg, torch.stack((Kdu, Kdv), dim=2).flatten(1, 2), Kdb), dim=1)
        y = fft_conv2d(x, K.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)
        return y.split((C, C, C, C), dim=1)

    else:
        return fft_conv2d(x, Kg.flatten(0, 1).unsqueeze(1), padding=(H-1, W-1), groups=C)

class GaussianMixtureServer(object):

    GM_SERVICE_NAME  = 'compute_gaussian_mixture'
    GML_SERVICE_NAME  = 'compute_gaussian_mixture_lambda'
    OGM_SERVICE_NAME = 'compute_oriented_gaussian_mixture'
    PEGM_SERVICE_NAME = 'compute_photometric_elliptical_gaussian_mixture'
    EGML_SERVICE_NAME  = 'compute_equirectangular_gaussian_mixture_lambda'

    def __init__(self):
        self.device = rospy.get_param('~device', 'cuda:0')
        self.gm_compute_srv = rospy.Service(self.GM_SERVICE_NAME, ComputeGaussianMixture, self.compute_gaussian_mixture)
        rospy.loginfo(f"Service 'gaussian_mixture_server/{self.GM_SERVICE_NAME}' advertised")
        self.gml_compute_srv = rospy.Service(self.GML_SERVICE_NAME, ComputeGaussianMixture, self.compute_gaussian_mixture_lambda)
        rospy.loginfo(f"Service 'gaussian_mixture_server/{self.GML_SERVICE_NAME}' advertised")
        self.ogm_compute_srv = rospy.Service(self.OGM_SERVICE_NAME, ComputeOrientedGaussianMixture, self.compute_oriented_gaussian_mixture)
        rospy.loginfo(f"Service 'gaussian_mixture_server/{self.OGM_SERVICE_NAME}' advertised")
        self.pegm_compute_srv = rospy.Service(self.PEGM_SERVICE_NAME, ComputePhotometricEllipticalGaussianMixture, self.compute_photometric_elliptical_gaussian_mixture)
        rospy.loginfo(f"Service 'gaussian_mixture_server/{self.PEGM_SERVICE_NAME}' advertised")
        self.egml_compute_srv = rospy.Service(self.EGML_SERVICE_NAME, ComputeGaussianMixture, self.compute_equirectangular_gaussian_mixture_lambda)
        rospy.loginfo(f"Service 'gaussian_mixture_server/{self.EGML_SERVICE_NAME}' advertised")

    def compute_gaussian_mixture(self, request):
        I = PILImage.fromarray(numpify(request.I), 'RGB').transpose(PILImage.FLIP_TOP_BOTTOM)
        I = Fv.to_tensor(I.convert('L')).unsqueeze(0).to(self.device)
        G, dGdu, dGdv, dGdb = gaussian_mixture(I, request.beta, derivatives=True)
        return ComputeGaussianMixtureResponse(
            msgify(Image, G.squeeze(0).permute(1, 2, 0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdu.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdv.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdb.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
        )

    def compute_gaussian_mixture_lambda(self, request):
        I = PILImage.fromarray(numpify(request.I), 'L')#.transpose(PILImage.FLIP_TOP_BOTTOM)
        I = Fv.to_tensor(I.convert('L')).unsqueeze(0).to(self.device)
        G, dGdu, dGdv, dGdb = gaussian_mixture_lambda(I, request.beta, derivatives=True)
        return ComputeGaussianMixtureResponse(
            msgify(Image, G.squeeze(0).permute(1, 2, 0).cpu().numpy(),     encoding="32FC1"),
            msgify(Image, dGdu.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdv.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdb.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
        )

    def compute_equirectangular_gaussian_mixture_lambda(self, request):
        I = PILImage.fromarray(numpify(request.I), 'L')
        I = Fv.to_tensor(I.convert('L')).unsqueeze(0).to(self.device)

        H, W = I.shape[-2:]
        flipped_half_top_left_I     = torch.flip(I[..., :H//2, :W//2], dims=[-2])
        flipped_half_top_right_I    = torch.flip(I[..., :H//2, W//2:], dims=[-2])
        flipped_half_bottom_left_I  = torch.flip(I[..., H//2:, :W//2], dims=[-2])
        flipped_half_bottom_right_I = torch.flip(I[..., H//2:, W//2:], dims=[-2])

        T_top    = torch.flip(torch.cat((flipped_half_top_right_I, flipped_half_top_left_I), dim=-1), dims=[-1])
        T_bottom = torch.flip(torch.cat((flipped_half_bottom_right_I, flipped_half_bottom_left_I), dim=-1), dims=[-1])
        T = torch.cat((T_top, I, T_bottom), dim=-2)
        #T = f.pad(T, (W, W, H//2, H//2), mode='circular')
        T = T[0,0,:,:]

        #Tiling the equirectangular image   #### !!!!! with my (NC) mistake !!!!! ######
        # I = I[0,0,:,:]
        # half_left_I = I[:, :I.shape[1] // 2]
        # half_right_I = I[:, I.shape[1] // 2:]
        # flipped_I = torch.flip(I, [0, 1])
        # flipped_half_left_I = torch.flip(half_left_I, [0, 1])
        # flipped_half_right_I = torch.flip(half_right_I, [0, 1])
        # T = torch.zeros(I.shape[0] * 5, I.shape[1] * 3).to(self.device)
        # T[:I.shape[0], :I.shape[1]] = I
        # T[:I.shape[0], I.shape[1]:2 * I.shape[1]] = I
        # T[:I.shape[0], 2 * I.shape[1]:] = I
        # T[I.shape[0]:2 * I.shape[0], :flipped_half_right_I.shape[1]] = flipped_half_left_I
        # T[I.shape[0]:2 * I.shape[0], flipped_half_right_I.shape[1]:flipped_half_right_I.shape[1] + flipped_I.shape[1]] = flipped_I
        # T[I.shape[0]:2 * I.shape[0], flipped_I.shape[1] + flipped_half_right_I.shape[1]:flipped_I.shape[1] * 2 + flipped_half_right_I.shape[1]] = flipped_I
        # T[I.shape[0]:2 * I.shape[0], flipped_I.shape[1] * 2 + flipped_half_right_I.shape[1]:] = flipped_half_right_I
        # T[2 * I.shape[0]:3 * I.shape[0], 0:T.shape[1]] = T[0:I.shape[0], 0:T.shape[1]]
        # T[3 * I.shape[0]:5 * I.shape[0], :] = T[I.shape[0]:3 * I.shape[0], :]

        #Tiling the equirectangular image
        # I = I[0,0,:,:]
        # half_left_I = I[:, :I.shape[1] // 2]
        # half_right_I = I[:, I.shape[1] // 2:]
        # flipped_I = torch.flip(I, [0, 1])
        # T = torch.zeros(I.shape[0] * 3, I.shape[1] * 2).to(self.device)
        # # Row 1: flipped_I | flipped_I
        # T[:I.shape[0], :I.shape[1]] = flipped_I
        # T[:I.shape[0], I.shape[1]:] = flipped_I
        # # Row 2: half_right_I | I | half_left_I
        # T[I.shape[0]:2*I.shape[0], :half_right_I.shape[1]] = half_right_I
        # T[I.shape[0]:2*I.shape[0], half_right_I.shape[1]:half_right_I.shape[1] + I.shape[1]] = I
        # T[I.shape[0]:2*I.shape[0], half_right_I.shape[1] + I.shape[1]:] = half_left_I
        # # Row 3: flipped_I | flipped_I
        # T[2*I.shape[0]:, :I.shape[1]] = flipped_I
        # T[2*I.shape[0]:, I.shape[1]:] = flipped_I

        # Save Binary Mask Tiling
        # tiled = T.detach().cpu().squeeze().numpy()
        # tiled_img = (tiled * 255).astype(np.uint8)
        # PILImage.fromarray(tiled_img).save("/home/hussein-loubani/PhD_CIAD/CODE/ros_noetic_visp_libper/share/Tiling/tiled_binary_mask.png")

        T = T.unsqueeze(0).unsqueeze(0)
        # start = time.time()
        G, dGdu, dGdv, dGdb = gaussian_mixture_lambda_circular(T, request.beta, derivatives=True)
        # end = time.time()
        # duration_ms = (end - start) * 1000.0
        # rospy.loginfo(f"[GM] gaussian_mixture_lambda computation time = {duration_ms:.2f} ms")
        # PILImage.fromarray((G.detach().cpu().squeeze().numpy() / G.max().cpu().detach().numpy() * 255).astype(np.uint8)).save("/home/hussein-loubani/PhD_CIAD/CODE/ros_noetic_visp_libper/share/Tiling/tiled_gaussian.png")

        G    = Fv.crop(G,    H//2, 0, H, W)
        dGdu = Fv.crop(dGdu, H//2, 0, H, W)
        dGdv = Fv.crop(dGdv, H//2, 0, H, W)
        dGdb = Fv.crop(dGdb, H//2, 0, H, W)

        # PILImage.fromarray((G.detach().cpu().squeeze().numpy() / G.max().cpu().detach().numpy() * 255).astype(np.uint8)).save("/home/hussein-loubani/PhD_CIAD/CODE/ros_noetic_visp_libper/share/Tiling/cropped_gaussian.png")

        # G = G[:, :, 2 * I.shape[0]:3*I.shape[0], I.shape[1]:2*I.shape[1]]
        # dGdu = dGdu[:, :, 2 * I.shape[0]:3*I.shape[0], I.shape[1]:2*I.shape[1]]
        # dGdv = dGdv[:, :, 2 * I.shape[0]:3*I.shape[0], I.shape[1]:2*I.shape[1]]
        # dGdb = dGdb[:, :, 2 * I.shape[0]:3*I.shape[0], I.shape[1]:2*I.shape[1]]

        #
        # G = G[:, :, I.shape[0]:2*I.shape[0], half_right_I.shape[1]:half_right_I.shape[1] + I.shape[1]]
        # dGdu = dGdu[:, :, I.shape[0]:2*I.shape[0], half_right_I.shape[1]:half_right_I.shape[1] + I.shape[1]]
        # dGdv = dGdv[:, :, I.shape[0]:2*I.shape[0], half_right_I.shape[1]:half_right_I.shape[1] + I.shape[1]]
        # dGdb = dGdb[:, :, I.shape[0]:2*I.shape[0], half_right_I.shape[1]:half_right_I.shape[1] + I.shape[1]]

        return ComputeGaussianMixtureResponse(
            msgify(Image, G.squeeze(0).permute(1, 2, 0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdu.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdv.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdb.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
        )


    def compute_oriented_gaussian_mixture(self, request):
        I = PILImage.fromarray(numpify(request.I), 'RGB').transpose(PILImage.FLIP_TOP_BOTTOM)
        I = Fv.to_tensor(I.convert('L')).unsqueeze(0).to(self.device)
        G, dGdu, dGdv, dGdb = oriented_gaussian_mixture(I, request.beta, request.ratio, request.theta, derivatives=True)
        return ComputeOrientedGaussianMixtureResponse(
            msgify(Image, G.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdu.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdv.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdb.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
        )

    def compute_photometric_elliptical_gaussian_mixture(self, request):
        I = PILImage.fromarray(numpify(request.I), 'RGB').transpose(PILImage.FLIP_TOP_BOTTOM)
        I = Fv.to_tensor(I.convert('L')).unsqueeze(0).to(self.device)
        G, dGdu, dGdv, dGdb = photometric_elliptical_gaussian_mixture(I, request.beta, request.ratio, request.theta, request.min, request.max, derivatives=True)
        return ComputePhotometricEllipticalGaussianMixtureResponse(
            msgify(Image, G.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdu.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdv.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
            msgify(Image, dGdb.squeeze(0).permute(1, 2,  0).cpu().numpy(), encoding="32FC1"),
        )


if __name__ == "__main__":
    rospy.init_node('gaussian_mixture_server')
    server = GaussianMixtureServer()
    rospy.spin()
